### ISSUE TITLE
Api Configuration from a Web Service

### ISSUE THREAD

**Issue by jb-berthet** [quanhua92/learn-opentok-android#1]
How can I set the ApiConfig class to make my app works?

**Comment by quanhua92** [comment]
You can check the opentok-php to generate token. https://github.com/opentok/learning-opentok-php
Basically, your app will need to connect to the API to generate a token, then both caller and callee app will use connect to the session id to talk to each other

**Comment by jb-berthet** [comment]
Thank you for your fast answer.
Now I'm working on an app using open source solutions, using libuvccamera and a simple WebRTC app.

**Comment by quanhua92** [comment]
Yeah. You're welcome. UVCCamera is very limited for production. Not all android devices support UVC.
